In [1]:
import torch
import numpy as np

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[9.2755e-39, 1.0561e-38, 8.1735e-39],
        [1.0102e-38, 8.4490e-39, 9.6428e-39],
        [1.1112e-38, 9.5511e-39, 1.0102e-38],
        [1.0286e-38, 1.0194e-38, 9.6429e-39],
        [9.2755e-39, 9.1837e-39, 9.3674e-39]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.1510, 0.4814, 0.3352],
        [0.1218, 0.3142, 0.6004],
        [0.4159, 0.3395, 0.9302],
        [0.4508, 0.6925, 0.7563],
        [0.2598, 0.9117, 0.1939]])


In [4]:
x = torch.zeros(5,4,dtype=torch.long)
print(x)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x.size()

torch.Size([2])

In [7]:
x = torch.rand(5,3)
y = torch.rand(5,3)

z1 = x + y
z2 = torch.add(x,y)

z3 = torch.empty(5,3)
torch.add(x,y,out=z3)

# in-place
y.add_(x) # _ 代表原地加法 也就是 y = y+x


# 可以想numpy数组一样使用tensor:
print(x[:,-1])

# Resizing, 利用torch.view来对tensor执行reshape/resize操作
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1,8) # -1代表自动推断维度
print(x.size(), y.size(), z.size()) # torch.Size([4,4]) torch.Size([16]) torch.Size([2,8])

tensor([0.9536, 0.6443, 0.7658, 0.0406, 0.5478])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [8]:
# item()可以获得只有一个元素的tensor的值
x = torch.randn(1)
print(x.item())

0.1674807369709015


In [9]:
a = torch.ones(5)
print(type(a)) # <class 'torch.Tensor'>
b = a.numpy()
print(type(b)) # <class 'numpy.ndarray'>

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [10]:
print(a.add_(1)) # tensor([2., 2., 2., 2., 2])
print(b) # [2., 2., 2., 2., 2]

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [11]:
a = np.ones(5)
b = torch.from_numpy(a)

In [13]:
if torch.cuda.is_available():
    device = torch.device("cuda") # 创建了一个cuda device对象
    y = torch.ones_like(x, device=device) # 直接从GPU上创建tensor
    x = x.to(device) # 将x移到gpu上, 也可以直接用字符串指明: x = x.to("cuda")
    z = x+y
    z.to("cpu", torch.double)